Refactor installation script
* global installation support

* single file installation

* Remove cat command dependency

* Store all required values in script itself

* Add a check if given path is outside user home dir

* Don't edit shell rc if given path is already present in ${PATH}

* Improve existing installtion checking

* change installed files perm, read + write for main script

* add a merge.sh script to create a merge scripts and make a standalone executable

Misc

* remove all GLOBALS comment in all function descriptions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,17 +34,19 @@ jobs:
       run: |
           set -e
           sh install.sh
-              . "${HOME}/.gdrive-downloader/gdrive-downloader.binpath"
+              PATH="${HOME}/.gdrive-downloader:${PATH}"
               gdl --info
           sh install.sh -U && sh install.sh --posix
-              . "${HOME}/.gdrive-downloader/gdrive-downloader.binpath"
+              PATH="${HOME}/.gdrive-downloader:${PATH}"
               gdl --info
           sh install.sh -U  && sh install.sh -c custom_gdl
-              . "${HOME}/.gdrive-downloader/gdrive-downloader.binpath"
+              PATH="${HOME}/.gdrive-downloader:${PATH}"
               custom_gdl --info
-    - name: 'Download'
+    - name: 'Merge and Download test'
       if: steps.filter.outputs.download == 'true'
       run: |
           set -e
+          sh merge.sh
+          { [ -n "$(git diff)" ] && printf "%s\n" "Error: Run merge.sh before pushing the commits" && exit 1 ;} || :
           brew reinstall bash 2> /dev/null 1>&2 || :
           sh test.sh
